cargo-features = ["strip"]

[workspace]

members = [
	"kernel",
	"boot/amd64",
	"drivers/virtio_block",
	"drivers/virtio_net",
	"lib/rust/endian",
	"lib/rust/pci",
	"lib/rust/virtio",
	"lib/rust/virtio_net",
	"lib/rust/volatile",
	"base/hello_std",
]

[profile.dev]
panic = "abort"
opt-level = 3

[profile.release]
panic = "abort"
lto = "fat"
#strip = "symbols"

[profile.release.package.noraboot]
codegen-units = 1
opt-level = 'z'
#strip = "symbols"
