cargo-features = ["strip"]

[workspace]

members = [
	"kernel",
	"boot/amd64"
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = "fat"
#strip = "symbols"

[profile.release.package.noraboot]
codegen-units = 1
opt-level = 'z'
#strip = "symbols"
