stdin = "uart/0"
stdout = "system/log"
stderr = "system/log"

[program.minish]
disabled = true
path = "minish"
file_root = ""
#stdin = "ps2_kbd/stream"
#after = [ "ps2_kbd/stream" ]

[program.fs_fat]
disabled = true
path = "fs-fat"
args = [ "file", "disk/data" ]
target = "file"
after = [ "disk/data" ]
file_root = ""

[program.virtio_blk]
disabled = true
path = "virtio-blk"
args = [ "disk" ]
target = "disk"
file_root = ""

[program.virtio_gpu]
path = "virtio-gpu"
args = [ "net" ]
target = "net"
file_root = ""

[program.virtio_net]
disabled = true
path = "virtio-net"
args = [ "net" ]
target = "net"
file_root = ""

[program.static_http_server]
disabled = true
path = "static_http_server"
after = [ "file", "net" ]
file_root = "file"
net_root = "net"

[program.scancode_to_char]
disabled = true
path = "scancode_to_char"
args = [ "ps2_kbd", "ps2_keyboard/scancodes" ]
after = [ "ps2_keyboard/scancodes" ]
file_root = ""

[program.intel_hd_graphics]
disabled = true
path = "intel_hd_graphics"
file_root = ""
