stdin = "uart/0"
stdout = "system/log"
stderr = "system/log"

[program.minish]
path = "minish"
file_root = ""
stdin = "ps2_kbd/stream"
after = [ "ps2_kbd/stream" ]

[program.fs_fat]
path = "fs-fat"
args = [ "file", "disk/data" ]
target = "file"
after = [ "disk/data" ]
file_root = ""

[program.virtio_blk]
path = "virtio-blk"
args = [ "disk" ]
target = "disk"
file_root = ""

[program.virtio_net]
path = "virtio-net"
args = [ "net" ]
target = "net"
file_root = ""

[program.static_http_server]
path = "static_http_server"
after = [ "file", "net" ]
file_root = "file"
net_root = "net"

# FIXME for some extremely bizarre reason using a 16-byte name makes
# toml-rs unable to see the "path" field. I suspect memory corruption (oh dear)
[program.scancode_to_char_]
path = "scancode_to_char"
args = [ "ps2_kbd", "ps2_keyboard/scancodes" ]
after = [ "ps2_keyboard/scancodes" ]
file_root = ""
