stdin = "uart/0"
stdout = "system/log"
stderr = "system/log"

[program.minish]
path = "minish"
file_root = ""
after = [ "gui_cli", "ps2_kbd/stream" ]
stdin = "ps2_kbd/stream"
stdout = "gui_cli/write"
stderr = "gui_cli/write"

[program.fs_fat]
disabled = true
path = "fs-fat"
args = [ "file", "disk/data" ]
target = "file"
after = [ "disk/data" ]
file_root = ""

[program.gui_cli]
path = "gui_cli"
after = [ "window_manager" ]
file_root = ""

[program.image_viewer]
path = "image_viewer"
after = [ "window_manager" ]
file_root = ""

[program.virtio_blk]
disabled = true
path = "virtio-blk"
args = [ "disk" ]
target = "disk"
file_root = ""

[program.virtio_gpu]
path = "virtio-gpu"
args = [ "gpu" ]
target = "net"
file_root = ""

[program.virtio_net]
path = "virtio-net"
args = [ "net" ]
target = "net"
file_root = ""

[program.static_http_server]
path = "static_http_server"
#after = [ "file", "net" ]
#file_root = "file"
after = [ "drivers", "net" ]
file_root = "drivers"
net_root = "net"

[program.scancode_to_char]
path = "scancode_to_char"
args = [ "ps2_kbd", "ps2_keyboard/scancodes" ]
after = [ "ps2_keyboard/scancodes" ]
file_root = ""

[program.intel_hd_graphics]
disabled = true
path = "intel_hd_graphics"
file_root = ""

[program.window_manager]
path = "window_manager"
after = [ "gpu/sync" ]
file_root = ""
