cargo-features = ["per-package-target"]

[package]
name = "nora"
version = "0.1.0"
edition = "2021"
default-target = "x86_64-unknown-none-norostbkernel"

[dependencies]
acpi = "*"
rsdp = "*"
pci = { path = "../lib/rust/pci" }
cfg-if = "1.0"

[features]
default = ["mem-max-16t", "driver-pci", "driver-hpet"]
mem-max-16t = []
mem-max-256m = []
driver-pci = []
driver-hpet = []
driver-pic = []

