[package]
name = "nora"
version = "0.1.0"
edition = "2021"

[dependencies]
acpi = "*"
rsdp = "*"
pci = { path = "../lib/rust/pci" }

[features]
default = ["mem-max-16t", "driver-pci", "driver-hpet"]
mem-max-16t = []
mem-max-256m = []
driver-pci = []
driver-hpet = []
driver-pic = []

