cargo-features = ["edition2021"]

[package]
name = "nora"
version = "0.1.0"
edition = "2021"

[dependencies]
acpi = "*"
rsdp = "*"

[features]
default = ["mem-max-16t"]
mem-max-16t = []
mem-max-256m = []
