[build]
target = "x86_64-unknown-norostb.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[target.x86_64-unknown-norostb]
runner = "./run.sh"
